# Generated by Django 4.2.6 on 2024-01-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept',
            old_name='d_location',
            new_name='dlocation',
        ),
        migrations.RenameField(
            model_name='dept',
            old_name='d_name',
            new_name='dname',
        ),
        migrations.AlterField(
            model_name='dept',
            name='d_id',
            field=models.IntegerField(),
        ),
    ]
